### ISSUE TITLE
scoping

### ISSUE THREAD

**Issue by x35a** [konstantinkobs/brackets-SASShints#1]
Hi, thanks a lot for extension! The question is about scoping.
Variables are visible inside single file. So if create a variable in file 1.scss, that variable isnt visible in 2.scss file.
Do you plan to implement scoping?

**Comment by elwinschmitz** [comment]
I would like that A LOT. :)

Don't know if it helps, but the TODO-extension(https://github.com/mikaeljorhult/brackets-todo) has a setting for it and can be set to search in all project-files.

But for Sass/Scss it makes sense to always search in all *.scss project-files, certainly when using scss-partials.

**Comment by konstantinkobs** [comment]
Hey guys,

thank you for your kind words. I found the code of that TODO-extension that is responsible for getting the contents of all stylesheets.

I will definitely take a look on how to adapt this to this extension. Unfortunately I don't have much time at the moment, but when I get to it, this should be a one-day-project. :wink:

**Comment by x35a** [comment]
Hi Konstantin, 

Thanks for prompt reply and solution. We'll be waiting.

**Comment by CydGoblin** [comment]
:+1:  +1! would love this

**Comment by marcofugaro** [comment]
Yes! This would be very useful, also because I usually save my variables in a _variable.scss partial file and then I import it.

**Comment by konstantinkobs** [comment]
Hey guys, sorry that I didn't have time for answering and developing a solution. I solved the problems and you get all variables of all SASS/SCSS files in your project. I hope, it is not too slow. If this is the case, give me some information about how many files you have in your project and so on and I will look for an alternative way to give you a good experience. :wink: 

Hope you like the update! :smile:

**Comment by x35a** [comment]
Hi Konstantin,
Extension woks fast and well, thank you! Spasibo!
